---
title: "Music Insight"
author: "Cody Evans"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---

## Importing data

```{r}
## install.packages('tidyverse')
suppressMessages(library("tidyverse"))

suppressMessages(surv <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/music-survey.csv"))
suppressMessages(pref <- read_csv("https://raw.githubusercontent.com/introdsci/MusicSurvey/master/preferences-survey.csv"))

N <- nrow(surv)

```

## Changing column names for better understanding

```{r}
colnames(surv)[colnames(surv) == "Timestamp"] <- "time_sub"
colnames(pref)[colnames(pref) == "Timestamp"] <- "time_sub"
colnames(surv)[colnames(surv) == "First, we are going to create a pseudonym for you to keep this survey anonymous (more or less). Which pseudonym generator would you prefer?"] <- "generator"
colnames(surv)[colnames(surv) == "What is your pseudonym?"] <- "name"
colnames(pref)[colnames(pref) == "What was your pseudonym?"] <- "name"
colnames(surv)[colnames(surv) == "Sex"] <- "sex"
colnames(surv)[colnames(surv) == "Major"] <- "major"
colnames(surv)[colnames(surv) == "Academic Year"] <- "grade_level"
colnames(surv)[colnames(surv) == "Year you were born (YYYY)"] <- "year_born"
colnames(surv)[colnames(surv) == "Which musical instruments/talents do you play? (Select all that apply)"] <- "instrument"
colnames(surv)[colnames(surv) == "Artist"] <- "song_artist"
colnames(surv)[colnames(surv) == "Song"] <- "song"
colnames(surv)[colnames(surv) == "Link to song (on Youtube or Vimeo)"] <- "link"
colnames(surv)

```

## Making some Nice Tibbles

```{r}
people <- tibble(generator = surv$generator, name = surv$name, sex = surv$sex, major = surv$major, grade_level = surv$grade_level, year_born = surv$year_born, instrument = surv$instrument, time = surv$time_sub)

song_list <- tibble(song_artist = surv$song_artist, song = surv$song, link = surv$link, name = surv$name)

tempPref <- pref[2:45]

temp <- gather(tempPref, key = "song_name", value = "rating", -name)

ratings <- tibble(persName = temp$name, songName = temp$song_name, rating = temp$rating)

people$time <- as.POSIXlt(parse_datetime(people$time, format = "%D %H:%M"))

for(n in 1:N) {
  if(identical(x = people$generator[n], y ="Fake rapper name generator")) {   
    people$generator[n] <- "rapper"
  } else {
    people$generator[n] <- "band"
  }
}

## install.packages("pracma")
suppressMessages(library("pracma"))
for(n in 1:N) {
  for(z in 1:N) {
    if(strcmpi(people$major[n], people$major[z])) {
      people$major[z] = people$major[n]
    }
  }
}
detach("package:pracma", unload=TRUE)

people$major <- as.factor(people$major)

levels(people$major)

```

## Making a simple graph

```{r fig.height=15, fig.width=20}

ratings$songName <- as.factor(ratings$songName)

(p <- ggplot(data = ratings, aes(songName, rating, colour = factor(songName))) + geom_count() + theme(axis.text.x = element_text(angle = 90)))

(p2 <- ggplot(ratings, aes(persName, rating, colour = factor(as.factor(persName)))) + geom_count() + theme(axis.text.x = element_text(angle = 90)))

(p3 <- ggplot(ratings, aes(persName, rating)) + geom_line() + theme(axis.text.x = element_text(angle = 90)))

```

## The graphs

```{r}
# Where song_name from ratings = song_name from people and persName from ratings = persName from people inner_join(ratings, people, by = song_name)
songs <- paste(surv$song_artist, surv$song, sep = "\t")

temp <- tibble(songName = songs, persName = surv$name)
joined <- dplyr::inner_join(ratings, temp, by = c("persName", "songName"))

notjoined <- dplyr::anti_join(temp, ratings, by = c("persName", "songName"))

mean(joined$rating)
```
